name: Maven CI/CD

on:
  push:
    branches: 
      - 'main'
    tags: [v*]
  workflow_dispatch:

jobs:
  build_and_coverage_report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Install test dependencies
        run: sudo apt-get -y -q --no-install-recommends install ffmpeg mediainfo tesseract-ocr tesseract-ocr-deu
      - name: Build with Maven
        run: mvn -B clean test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: >
            docs-core/target/site/jacoco/jacoco.csv
            docs-web/target/site/jacoco/jacoco.csv
            docs-web-common/target/site/jacoco/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      
      - name: Commit badge
        run: |
          mkdir tmp
          cp .github/badges/*.svg tmp 
          git checkout -b badges
          mkdir -p badges
          cp ./tmp/*.svg badges
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add './badges/*.svg'
          git commit -m "Add/Update badge"
        continue-on-error: true

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges
          force: true



     
